= Example Containerized JaxRS Service
:toc: left
:source-highlighter: pygments
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

[NOTE]
This repository is a thin demonstrative wrapper around the
https://github.com/VEuPathDB/lib-jaxrs-container-core[Core container library],
for more in depth documentation of available features and config options see
the core library's readme.

== Running the Example

=== Locally

==== Prerequisites

* Maven
* NodeJS/NPM
* Github credentials providing access to https://github.com/VEuPathDB/maven-packages[VEuPathDB packages]
* Java v21+

==== Setup & Run

Environment/dependency setup for local development can be done via the command
`make install-dev-env`.  This will install the dependencies required to build the
project.

After the environment has been set up, the project can be built, tested, and
packaged using `make jar`.

Starting the server can be done by running `java -jar build/libs/service.jar`.

[WARNING]
--
Most projects will require some CLI or environment arguments to run.  For a full
listing of available options see the
https://github.com/VEuPathDB/lib-jaxrs-container-core[core container library]
documentation.
--

[NOTE]
--
All project specific system level dependencies must be installed locally for
this to work.
--

=== In Docker

==== Prerequisites

* Docker
* Docker Compose

==== Setup & Run

The project container can be built using `make docker`.  The first build
of the container will take several minutes.

Running the built container can be done with:
----
$ docker compose -f docker/docker-compose.dev.yml up
----

[WARNING]
--
Most projects will require some CLI or environment arguments to run.  For a full
listing of available options see the
https://github.com/VEuPathDB/lib-jaxrs-container-core[core container library]
documentation.  When using docker-compose these options can be
https://docs.docker.com/compose/environment-variables/[set automatically]
through the use of a `.env` file.
--


//------------------------------------------------------------------------------


== Development

TODO

Run `make` in the project directory to see available make targets.

Run `./gradlew tasks` to see available gradle tasks.

